version: '3.8'

services:
  dbgenerator:
    environment:
      # Debug w VS
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    volumes:
      # Hot reload dla development
      - .:/app
      - ~/.nuget/packages:/root/.nuget/packages:ro
    working_dir: /app
